@startuml
left to right direction
skinparam actorStyle awesome

rectangle "Application Mobile" {
  actor Conducteur
  (S'authentifier) as AuthMobile
  (Consulter missions)
  (Géolocalisation GPS)
  (Valider étapes)
  (Clôturer mission)
  
  Conducteur --> (Consulter missions)
  Conducteur --> (Géolocalisation GPS)
  Conducteur --> (Valider étapes)
  Conducteur --> (Clôturer mission)
  
  (Consulter missions) ..> AuthMobile : <<include>>
  (Géolocalisation GPS) ..> AuthMobile : <<include>>
  (Valider étapes) ..> AuthMobile : <<include>>
  (Clôturer mission) ..> AuthMobile : <<include>>
}

rectangle "Page Web" {
  actor Client
  (S'authentifier) as AuthWeb
  (Passer commande)
  (Confirmer commande)
  
  Client --> (Passer commande)
  Client --> (Confirmer commande)
  
  (Passer commande) ..> AuthWeb : <<include>>
  (Confirmer commande) ..> AuthWeb : <<include>>
}

rectangle "Application Desktop" {
  actor Gestionnaire
  (S'authentifier) as AuthDesktop
  (Gérer chantiers)
  (Planifier tournées)
  (Optimiser transferts)
  (Visualiser KPI)
  (Carte interactive)
  (Traiter commandes)
  (Affecter conducteurs)
  (Affecter véhicules)
  
  Gestionnaire --> (Gérer chantiers)
  Gestionnaire --> (Planifier tournées)
  Gestionnaire --> (Optimiser transferts)
  Gestionnaire --> (Visualiser KPI)
  Gestionnaire --> (Carte interactive)
  Gestionnaire --> (Traiter commandes)
  Gestionnaire --> (Affecter conducteurs)
  Gestionnaire --> (Affecter véhicules)
  
  (Gérer chantiers) ..> AuthDesktop : <<include>>
  (Planifier tournées) ..> AuthDesktop : <<include>>
  (Optimiser transferts) ..> AuthDesktop : <<include>>
  (Visualiser KPI) ..> AuthDesktop : <<include>>
  (Carte interactive) ..> AuthDesktop : <<include>>
  (Traiter commandes) ..> AuthDesktop : <<include>>
  (Affecter conducteurs) ..> AuthDesktop : <<include>>
  (Affecter véhicules) ..> AuthDesktop : <<include>>
}

rectangle "Application Gestion Matériel" {
  actor "Assistant Administratif" as Assistant
  (S'authentifier) as AuthMateriel
  (Gérer disponibilité véhicules)
  (Gérer équipements)
  
  Assistant --> (Gérer disponibilité véhicules)
  Assistant --> (Gérer équipements)
  
  (Gérer disponibilité véhicules) ..> AuthMateriel : <<include>>
  (Gérer équipements) ..> AuthMateriel : <<include>>
}

rectangle "Application RH" {
  actor "Assistant RH" as AssistantRH
  (S'authentifier) as AuthRH
  (Gérer informations conducteurs)
  (Gérer congés conducteurs)
  
  AssistantRH --> (Gérer informations conducteurs)
  AssistantRH --> (Gérer congés conducteurs)
  
  (Gérer informations conducteurs) ..> AuthRH : <<include>>
  (Gérer congés conducteurs) ..> AuthRH : <<include>>
}

@enduml