"""ajoute de la table transferer equipemeents 

Revision ID: 08a4f6b1ff02
Revises: 617884a85c84
Create Date: 2025-03-17 13:54:08.539469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08a4f6b1ff02'
down_revision: Union[str, None] = '617884a85c84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transferer_equipement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('volet', sa.String(255), nullable=False),
    sa.Column('designation_equipement', sa.String(255), nullable=False),
    sa.Column('total_equipements', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('semaine_transfert',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('equipement_id', sa.Integer(), nullable=False),
    sa.Column('numero_semaine', sa.Integer(), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equipement_id'], ['transferer_equipement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('semaine_transfert')
    op.drop_table('transferer_equipement')
    # ### end Alembic commands ###
