"""ajoute de la colonne modalite transport 

Revision ID: 08fab29d8718
Revises: 08a4f6b1ff02
Create Date: 2025-03-18 01:34:44.838425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '08fab29d8718'
down_revision: Union[str, None] = '08a4f6b1ff02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('semaine_transfert', sa.Column('id_equipement', sa.Integer(), nullable=False))
    op.drop_constraint('semaine_transfert_ibfk_1', 'semaine_transfert', type_='foreignkey')
    op.create_foreign_key(None, 'semaine_transfert', 'transferer_equipement', ['id_equipement'], ['id'])
    op.drop_column('semaine_transfert', 'equipement_id')
    op.add_column('transferer_equipement', sa.Column('modalite_transport', sa.String(length=255), nullable=True))
    op.alter_column('transferer_equipement', 'volet',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transferer_equipement', 'volet',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('transferer_equipement', 'modalite_transport')
    op.add_column('semaine_transfert', sa.Column('equipement_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'semaine_transfert', type_='foreignkey')
    op.create_foreign_key('semaine_transfert_ibfk_1', 'semaine_transfert', 'transferer_equipement', ['equipement_id'], ['id'])
    op.drop_column('semaine_transfert', 'id_equipement')
    # ### end Alembic commands ###
