"""ajoute la colonne duree

Revision ID: 16ced6455ba8
Revises: bf74ad39fa49
Create Date: 2025-03-16 13:00:33.121699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16ced6455ba8'
down_revision: Union[str, None] = 'bf74ad39fa49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournees', sa.Column('duree', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournees', 'duree')
    # ### end Alembic commands ###
