"""Ajout colonne statut à Commande

Revision ID: 1d199f348d3f
Revises: 57ac597b748b
Create Date: 2025-05-27 09:37:00.738285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d199f348d3f'
down_revision: Union[str, None] = '57ac597b748b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commandes', sa.Column('statut', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commandes', 'statut')
    # ### end Alembic commands ###
