"""Ajout des relations chantier, équipements, transfert

Revision ID: 359a9816ad67
Revises: af12dd0530db
Create Date: 2025-03-25 01:23:43.819624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '359a9816ad67'
down_revision: Union[str, None] = 'af12dd0530db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chantiers', sa.Column('id_chantier', sa.Integer(), nullable=False))
    op.drop_column('chantiers', 'id_client')
    op.add_column('commandes', sa.Column('id_chantier', sa.Integer(), nullable=True))
    op.drop_constraint('commandes_ibfk_2', 'commandes', type_='foreignkey')
    op.create_foreign_key(None, 'commandes', 'chantiers', ['id_chantier'], ['id_chantier'])
    op.drop_column('commandes', 'id_client')
    op.add_column('transferer_equipement', sa.Column('id_equipement', sa.Integer(), nullable=False))
    op.drop_constraint('transferer_equipement_ibfk_1', 'transferer_equipement', type_='foreignkey')
    op.create_foreign_key(None, 'transferer_equipement', 'chantiers', ['id_chantier'], ['id_chantier'])
    op.create_foreign_key(None, 'transferer_equipement', 'equipements', ['id_equipement'], ['ID_equipement'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transferer_equipement', type_='foreignkey')
    op.drop_constraint(None, 'transferer_equipement', type_='foreignkey')
    op.create_foreign_key('transferer_equipement_ibfk_1', 'transferer_equipement', 'chantiers', ['id_chantier'], ['id_client'])
    op.drop_column('transferer_equipement', 'id_equipement')
    op.add_column('commandes', sa.Column('id_client', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'commandes', type_='foreignkey')
    op.create_foreign_key('commandes_ibfk_2', 'commandes', 'chantiers', ['id_client'], ['id_client'])
    op.drop_column('commandes', 'id_chantier')
    op.add_column('chantiers', sa.Column('id_client', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.drop_column('chantiers', 'id_chantier')
    # ### end Alembic commands ###
