"""ajout de la colonne date heure darrivee

Revision ID: 3c77ae1d6457
Revises: 3f65958392e8
Create Date: 2025-03-16 12:05:05.406436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c77ae1d6457'
down_revision: Union[str, None] = '3f65958392e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournees', sa.Column('date_heure_arrivee', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournees', 'date_heure_arrivee')
    # ### end Alembic commands ###
