"""l migration

Revision ID: 3f65958392e8
Revises: ff4684ede9a9
Create Date: 2025-03-16 00:07:08.905789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3f65958392e8'
down_revision: Union[str, None] = 'ff4684ede9a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commandes_equipements',
    sa.Column('id_commande', sa.Integer(), nullable=False),
    sa.Column('ID_equipement', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ID_equipement'], ['equipements.ID_equipement'], ),
    sa.ForeignKeyConstraint(['id_commande'], ['commandes.id_commande'], ),
    sa.PrimaryKeyConstraint('id_commande', 'ID_equipement')
    )
    op.drop_constraint('commandes_ibfk_1', 'commandes', type_='foreignkey')
    op.drop_column('commandes', 'ID_equipement')
    op.add_column('conducteurs', sa.Column('disponibilite', sa.Enum('disponible', 'conge', 'autres', name='disponibilite_enum'), nullable=False))
    op.add_column('conducteurs', sa.Column('commentaire_disponibilite', sa.String(length=255), nullable=True))
    op.alter_column('conducteurs', 'nom',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('conducteurs', 'prenom',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('conducteurs', 'numero_telephone',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('conducteurs', 'categorie',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('etapes_rotation', 'date_heure_depart')
    op.drop_column('etapes_rotation', 'type')
    op.drop_column('etapes_rotation', 'lieu_dechargement')
    op.drop_column('etapes_rotation', 'lieu_chargement')
    op.drop_column('etapes_rotation', 'duree')
    op.drop_column('etapes_rotation', 'date_heure_arrivee')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etapes_rotation', sa.Column('date_heure_arrivee', mysql.DATETIME(), nullable=True))
    op.add_column('etapes_rotation', sa.Column('duree', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('etapes_rotation', sa.Column('lieu_chargement', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('etapes_rotation', sa.Column('lieu_dechargement', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('etapes_rotation', sa.Column('type', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('etapes_rotation', sa.Column('date_heure_depart', mysql.DATETIME(), nullable=True))
    op.alter_column('conducteurs', 'categorie',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('conducteurs', 'numero_telephone',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('conducteurs', 'prenom',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('conducteurs', 'nom',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('conducteurs', 'commentaire_disponibilite')
    op.drop_column('conducteurs', 'disponibilite')
    op.add_column('commandes', sa.Column('ID_equipement', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('commandes_ibfk_1', 'commandes', 'equipements', ['ID_equipement'], ['ID_equipement'])
    op.drop_table('commandes_equipements')
    # ### end Alembic commands ###
