"""Ajout clé étrangère id_equipement à Commande

Revision ID: 57ac597b748b
Revises: ab800866195b
Create Date: 2025-05-26 22:27:36.725927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '57ac597b748b'
down_revision: Union[str, None] = 'ab800866195b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_segments_date_creation', table_name='segments')
    op.drop_index('idx_segments_distance', table_name='segments')
    op.drop_index('idx_segments_point1_coords', table_name='segments')
    op.drop_index('idx_segments_point2_coords', table_name='segments')
    op.drop_table('segments')
    op.add_column('commandes', sa.Column('id_equipement', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'commandes', 'equipements', ['id_equipement'], ['ID_equipement'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'commandes', type_='foreignkey')
    op.drop_column('commandes', 'id_equipement')
    op.create_table('segments',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('point1_nom', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('point1_latitude', mysql.FLOAT(), nullable=False),
    sa.Column('point1_longitude', mysql.FLOAT(), nullable=False),
    sa.Column('point1_type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('point1_id_reference', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('point2_nom', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('point2_latitude', mysql.FLOAT(), nullable=False),
    sa.Column('point2_longitude', mysql.FLOAT(), nullable=False),
    sa.Column('point2_type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('point2_id_reference', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('distance_km', mysql.FLOAT(), nullable=False),
    sa.Column('couleur', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('epaisseur', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('afficher_distance', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('nom_segment', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('date_creation', mysql.DATETIME(), nullable=True),
    sa.Column('date_modification', mysql.DATETIME(), nullable=True),
    sa.Column('cree_par', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_segments_point2_coords', 'segments', ['point2_latitude', 'point2_longitude'], unique=False)
    op.create_index('idx_segments_point1_coords', 'segments', ['point1_latitude', 'point1_longitude'], unique=False)
    op.create_index('idx_segments_distance', 'segments', ['distance_km'], unique=False)
    op.create_index('idx_segments_date_creation', 'segments', ['date_creation'], unique=False)
    # ### end Alembic commands ###
