"""Mise à jour après suppression id_chantier

Revision ID: 60cb09320076
Revises: e0d6cf555852
Create Date: 2025-03-26 22:46:59.674419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '60cb09320076'
down_revision: Union[str, None] = 'e0d6cf555852'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chantiers', 'id_client',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_column('chantiers', 'id_chantier')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chantiers', sa.Column('id_chantier', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.alter_column('chantiers', 'id_client',
               existing_type=sa.String(length=255),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
    # ### end Alembic commands ###
