"""ajoute la colonne temps daller 

Revision ID: 617884a85c84
Revises: 16ced6455ba8
Create Date: 2025-03-16 16:12:10.335117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '617884a85c84'
down_revision: Union[str, None] = '16ced6455ba8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chantiers', sa.Column('temps_aller', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chantiers', 'temps_aller')
    # ### end Alembic commands ###
