"""Ajout de la colonne etat pour les  véhicules

Revision ID: 72af84f2ba78
Revises: b38ba2d40a2b
Create Date: 2025-03-14 23:58:17.439147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72af84f2ba78'
down_revision: Union[str, None] = 'b38ba2d40a2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicules', sa.Column('etat', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicules', 'etat')
    # ### end Alembic commands ###
