"""Ajout colonne 12_semaines_avant_la_fin

Revision ID: a8fae3d8eaab
Revises: bd109029d7fc
Create Date: 2025-04-09 19:21:28.863107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a8fae3d8eaab'
down_revision: Union[str, None] = 'bd109029d7fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('semaine_transfert')
    op.add_column('transferer_equipement', sa.Column("12_semaines_avant_la_fin_de_l'ancien_projet", sa.Integer(), nullable=True))
    op.add_column('transferer_equipement', sa.Column("11_semaines_avant_la_fin_de_l'ancien_projet", sa.Integer(), nullable=True))
    op.add_column('transferer_equipement', sa.Column("10_semaines_avant_la_fin_de_l'ancien_projet", sa.Integer(), nullable=True))
    op.add_column('transferer_equipement', sa.Column("9_semaines_avant_la_fin_de_l'ancien_projet", sa.Integer(), nullable=True))
    op.add_column('transferer_equipement', sa.Column("8_semaines_avant_la_fin_de_l'ancien_projet", sa.Integer(), nullable=True))
    op.add_column('transferer_equipement', sa.Column("7_semaines_avant_la_fin_de_l'ancien_projet", sa.Integer(), nullable=True))
    op.add_column('transferer_equipement', sa.Column("6_semaines_avant_la_fin_de_l'ancien_projet", sa.Integer(), nullable=True))
    op.add_column('transferer_equipement', sa.Column("5_semaines_avant_la_fin_de_l'ancien_projet", sa.Integer(), nullable=True))
    op.add_column('transferer_equipement', sa.Column("4_semaines_avant_la_fin_de_l'ancien_projet", sa.Integer(), nullable=True))
    op.add_column('transferer_equipement', sa.Column("3_semaines_avant_la_fin_de_l'ancien_projet", sa.Integer(), nullable=True))
    op.add_column('transferer_equipement', sa.Column("2_semaines_avant_la_fin_de_l'ancien_projet", sa.Integer(), nullable=True))
    op.add_column('transferer_equipement', sa.Column("1_semaines_avant_la_fin_de_l'ancien_projet", sa.Integer(), nullable=True))
    op.add_column('transferer_equipement', sa.Column("0_semaines_avant_la_fin_de_l'ancien_projet", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transferer_equipement', "0_semaines_avant_la_fin_de_l'ancien_projet")
    op.drop_column('transferer_equipement', "1_semaines_avant_la_fin_de_l'ancien_projet")
    op.drop_column('transferer_equipement', "2_semaines_avant_la_fin_de_l'ancien_projet")
    op.drop_column('transferer_equipement', "3_semaines_avant_la_fin_de_l'ancien_projet")
    op.drop_column('transferer_equipement', "4_semaines_avant_la_fin_de_l'ancien_projet")
    op.drop_column('transferer_equipement', "5_semaines_avant_la_fin_de_l'ancien_projet")
    op.drop_column('transferer_equipement', "6_semaines_avant_la_fin_de_l'ancien_projet")
    op.drop_column('transferer_equipement', "7_semaines_avant_la_fin_de_l'ancien_projet")
    op.drop_column('transferer_equipement', "8_semaines_avant_la_fin_de_l'ancien_projet")
    op.drop_column('transferer_equipement', "9_semaines_avant_la_fin_de_l'ancien_projet")
    op.drop_column('transferer_equipement', "10_semaines_avant_la_fin_de_l'ancien_projet")
    op.drop_column('transferer_equipement', "11_semaines_avant_la_fin_de_l'ancien_projet")
    op.drop_column('transferer_equipement', "12_semaines_avant_la_fin_de_l'ancien_projet")
    op.create_table('semaine_transfert',
    sa.Column('numero_semaine', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('quantite', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('id_semaine', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('id_equipement', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_equipement'], ['transferer_equipement.id'], name='semaine_transfert_ibfk_1'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
