"""Ajout de la colonne etat pour les véhicules

Revision ID: af12dd0530db
Revises: 08fab29d8718
Create Date: 2025-03-24 11:26:41.123438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af12dd0530db'
down_revision: Union[str, None] = '08fab29d8718'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transferer_equipement', sa.Column('id_chantier', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'transferer_equipement', 'chantiers', ['id_chantier'], ['id_client'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transferer_equipement', type_='foreignkey')
    op.drop_column('transferer_equipement', 'id_chantier')
    # ### end Alembic commands ###
