"""Initial migration

Revision ID: b38ba2d40a2b
Revises: 
Create Date: 2025-03-14 12:33:46.427319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b38ba2d40a2b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Table `chantiers` (doit être créée en premier car elle est référencée par `commandes`)
    if not op.get_bind().engine.dialect.has_table(op.get_bind(), 'chantiers'):
        op.create_table('chantiers',
            sa.Column('id_client', sa.Integer(), nullable=False),
            sa.Column('localisation', sa.String(length=255), nullable=True),
            sa.Column('latitude', sa.Float(), nullable=True),
            sa.Column('longitude', sa.Float(), nullable=True),
            sa.Column('nature_terrain', sa.String(length=255), nullable=True),
            sa.Column('distanceAllerGoudron', sa.Float(), nullable=True),
            sa.Column('distanceAllerPiste', sa.Float(), nullable=True),
            sa.PrimaryKeyConstraint('id_client')
        )

    # Table `equipements` (doit être créée avant `commandes` car elle est référencée par `commandes`)
    if not op.get_bind().engine.dialect.has_table(op.get_bind(), 'equipements'):
        op.create_table('equipements',
            sa.Column('ID_equipement', sa.Integer(), autoincrement=True, nullable=False),
            sa.Column('quantite', sa.Integer(), nullable=True),
            sa.Column('nomEquipement', sa.String(length=255), nullable=True),
            sa.Column('typeEquipement', sa.String(length=255), nullable=True),
            sa.Column('etat', sa.String(length=255), nullable=True),
            sa.PrimaryKeyConstraint('ID_equipement')
        )

    # Table `commandes` (référence `chantiers` et `equipements`)
    if not op.get_bind().engine.dialect.has_table(op.get_bind(), 'commandes'):
        op.create_table('commandes',
            sa.Column('id_commande', sa.Integer(), autoincrement=True, nullable=False),
            sa.Column('id_client', sa.Integer(), nullable=True),
            sa.Column('nature_service', sa.String(length=255), nullable=True),
            sa.Column('type_vehicule', sa.String(length=255), nullable=True),
            sa.Column('ID_equipement', sa.Integer(), nullable=True),
            sa.Column('quantite_requise', sa.Float(), nullable=True),
            sa.Column('lieu_chargement', sa.String(length=255), nullable=True),
            sa.Column('date_commande', sa.DateTime(), nullable=True),
            sa.Column('date_livraison', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['ID_equipement'], ['equipements.ID_equipement'], ),
            sa.ForeignKeyConstraint(['id_client'], ['chantiers.id_client'], ),
            sa.PrimaryKeyConstraint('id_commande')
        )

    # Table `conducteurs`
    if not op.get_bind().engine.dialect.has_table(op.get_bind(), 'conducteurs'):
        op.create_table('conducteurs',
            sa.Column('id_conducteur', sa.String(length=255), nullable=False),
            sa.Column('nom', sa.String(length=255), nullable=True),
            sa.Column('prenom', sa.String(length=255), nullable=True),
            sa.Column('numero_telephone', sa.String(length=255), nullable=True),
            sa.Column('categorie', sa.String(length=255), nullable=True),
            sa.PrimaryKeyConstraint('id_conducteur')
        )

    # Table `vehicules`
    if not op.get_bind().engine.dialect.has_table(op.get_bind(), 'vehicules'):
        op.create_table('vehicules',
            sa.Column('immatriculation', sa.String(length=255), nullable=False),
            sa.Column('numero_chassis', sa.String(length=255), nullable=True),
            sa.Column('numero_interne', sa.String(length=255), nullable=True),
            sa.Column('marque_modele', sa.String(length=255), nullable=True),
            sa.Column('type_vehicule', sa.String(length=255), nullable=True),
            sa.Column('capacite_tonne', sa.Float(), nullable=True),
            sa.Column('capacite_volume', sa.Float(), nullable=True),
            sa.PrimaryKeyConstraint('immatriculation')
        )

    # Table `tournees` (référence `commandes`, `conducteurs` et `vehicules`)
    if not op.get_bind().engine.dialect.has_table(op.get_bind(), 'tournees'):
        op.create_table('tournees',
            sa.Column('id_tournee', sa.Integer(), autoincrement=True, nullable=False),
            sa.Column('id_conducteur', sa.String(length=255), nullable=True),
            sa.Column('immatriculation_vehicule', sa.String(length=255), nullable=True),
            sa.Column('id_commande', sa.Integer(), nullable=True),
            sa.Column('objectif', sa.String(length=255), nullable=True),
            sa.Column('lieu_depart', sa.String(length=255), nullable=True),
            sa.Column('destination', sa.String(length=255), nullable=True),
            sa.Column('itineraire', sa.String(length=255), nullable=True),
            sa.Column('km_parcouru', sa.Float(), nullable=True),
            sa.Column('date_heure_depart', sa.DateTime(), nullable=True),
            sa.Column('date_heure_reception', sa.DateTime(), nullable=True),
            sa.Column('date_heure_retour', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['id_commande'], ['commandes.id_commande'], ),
            sa.ForeignKeyConstraint(['id_conducteur'], ['conducteurs.id_conducteur'], ),
            sa.ForeignKeyConstraint(['immatriculation_vehicule'], ['vehicules.immatriculation'], ),
            sa.PrimaryKeyConstraint('id_tournee')
        )

    # Table `affectations` (référence `conducteurs`, `vehicules` et `tournees`)
    if not op.get_bind().engine.dialect.has_table(op.get_bind(), 'affectations'):
        op.create_table('affectations',
            sa.Column('id_affectation', sa.Integer(), autoincrement=True, nullable=False),
            sa.Column('id_conducteur', sa.String(length=255), nullable=True),
            sa.Column('immatriculation_vehicule', sa.String(length=255), nullable=True),
            sa.Column('id_tournee', sa.Integer(), nullable=True),
            sa.Column('date_affectation', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['id_conducteur'], ['conducteurs.id_conducteur'], ),
            sa.ForeignKeyConstraint(['id_tournee'], ['tournees.id_tournee'], ),
            sa.ForeignKeyConstraint(['immatriculation_vehicule'], ['vehicules.immatriculation'], ),
            sa.PrimaryKeyConstraint('id_affectation')
        )

    # Table `etapes_rotation` (référence `tournees`)
    if not op.get_bind().engine.dialect.has_table(op.get_bind(), 'etapes_rotation'):
        op.create_table('etapes_rotation',
            sa.Column('id_etape', sa.Integer(), autoincrement=True, nullable=False),
            sa.Column('id_tournee', sa.Integer(), nullable=True),
            sa.Column('lieu_chargement', sa.String(length=255), nullable=True),
            sa.Column('lieu_dechargement', sa.String(length=255), nullable=True),
            sa.Column('date_heure_depart', sa.DateTime(), nullable=True),
            sa.Column('date_heure_arrivee', sa.DateTime(), nullable=True),
            sa.Column('duree', sa.String(length=255), nullable=True),
            sa.Column('type', sa.String(length=255), nullable=True),
            sa.ForeignKeyConstraint(['id_tournee'], ['tournees.id_tournee'], ),
            sa.PrimaryKeyConstraint('id_etape')
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('etapes_rotation')
    op.drop_table('affectations')
    op.drop_table('tournees')
    op.drop_table('vehicules')
    op.drop_table('conducteurs')
    op.drop_table('commandes')
    op.drop_table('equipements')
    op.drop_table('chantiers')
    # ### end Alembic commands ###