"""Fix de la migration

Revision ID: bfc089ac6f79
Revises: dea31f687f91
Create Date: 2025-04-08 21:20:21.602738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bfc089ac6f79'
down_revision: Union[str, None] = 'dea31f687f91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'commandes_equipements', 'equipements', ['IDentificaton_equipe'], ['IDentificaton_equipe'])
    op.drop_column('commandes_equipements', 'ID_equipement')
    op.add_column('equipements', sa.Column('IDentificaton_equipe', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_column('equipements', 'ID_equipement')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipements', sa.Column('ID_equipement', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.drop_column('equipements', 'IDentificaton_equipe')
    op.add_column('commandes_equipements', sa.Column('ID_equipement', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'commandes_equipements', type_='foreignkey')
    # ### end Alembic commands ###
