"""changement de la classe semaine

Revision ID: c713b5d61aec
Revises: db45c8177d64
Create Date: 2025-03-30 13:37:35.451214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c713b5d61aec'
down_revision: Union[str, None] = 'db45c8177d64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('semaine_transfert', sa.Column('id_semaine', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_constraint('semaine_transfert_ibfk_1', 'semaine_transfert', type_='foreignkey')
    op.create_foreign_key(None, 'semaine_transfert', 'transferer_equipement', ['id'], ['id'])
    op.drop_column('semaine_transfert', 'id_equipement')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('semaine_transfert', sa.Column('id_equipement', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'semaine_transfert', type_='foreignkey')
    op.create_foreign_key('semaine_transfert_ibfk_1', 'semaine_transfert', 'transferer_equipement', ['id_equipement'], ['id'])
    op.drop_column('semaine_transfert', 'id_semaine')
    # ### end Alembic commands ###
