"""Nouvelle migration

Revision ID: db45c8177d64
Revises: 60cb09320076
Create Date: 2025-03-27 12:31:35.715006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'db45c8177d64'
down_revision: Union[str, None] = '60cb09320076'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chantiers', 'id_chantier')
    op.create_foreign_key(None, 'transferer_equipement', 'chantiers', ['id_client'], ['id_client'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transferer_equipement', type_='foreignkey')
    op.add_column('chantiers', sa.Column('id_chantier', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
