"""message

Revision ID: dec33e9c360d
Revises: dea31f687f91
Create Date: 2025-04-09 13:51:42.939236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dec33e9c360d'
down_revision: Union[str, None] = 'dea31f687f91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'commandes_equipements', 'equipements', ['ID_equipement'], ['ID_equipement'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'commandes_equipements', type_='foreignkey')
    # ### end Alembic commands ###
