"""id_equipement fixation

Revision ID: e28b39add2e7
Revises: dec33e9c360d
Create Date: 2025-04-09 14:17:58.976629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e28b39add2e7'
down_revision: Union[str, None] = 'dec33e9c360d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('semaine_transfert', sa.Column('id_equipement', sa.Integer(), nullable=False))
    op.drop_constraint('semaine_transfert_ibfk_1', 'semaine_transfert', type_='foreignkey')
    op.create_foreign_key(None, 'semaine_transfert', 'transferer_equipement', ['id_equipement'], ['id'])
    op.drop_column('semaine_transfert', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('semaine_transfert', sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'semaine_transfert', type_='foreignkey')
    op.create_foreign_key('semaine_transfert_ibfk_1', 'semaine_transfert', 'transferer_equipement', ['id'], ['id'])
    op.drop_column('semaine_transfert', 'id_equipement')
    # ### end Alembic commands ###
