"""Ajout colonne poids et volume

Revision ID: f07411cec94f
Revises: a8fae3d8eaab
Create Date: 2025-04-29 18:50:27.625670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f07411cec94f'
down_revision: Union[str, None] = 'a8fae3d8eaab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipements', sa.Column('poids', sa.Float(), nullable=True, comment="Poids de l'équipement en kilogrammes"))
    op.add_column('equipements', sa.Column('volume', sa.Float(), nullable=True, comment="Volume de l'équipement en mètres cubes"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipements', 'volume')
    op.drop_column('equipements', 'poids')
    # ### end Alembic commands ###
