"""Ajout du type ENUM pour la colonne etat

Revision ID: ff4684ede9a9
Revises: 72af84f2ba78
Create Date: 2025-03-15 12:19:31.658376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ff4684ede9a9'
down_revision: Union[str, None] = '72af84f2ba78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicules', 'etat',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Enum('Disponible', 'En panne', 'En service', name='etat_vehicule_enum'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicules', 'etat',
               existing_type=sa.Enum('Disponible', 'En panne', 'En service', name='etat_vehicule_enum'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
